name: Matlab

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash
    working-directory: dlib/matlab


jobs:
  mex-wrapper:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v1
    - name: Compile mex wrappers 
      run: |
        pwd
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release --target install --parallel 4
    - name: run mex example
      run: |
        cd ..
        matlab -nodisplay -h
        matlab -h
        which matlab
        matlab -nodisplay -r 'try, example(), catch, exit(1); end; exit'


